# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - pocwebapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and Start virtual environment and Install dependencies
        run: |
          cd app-service               # 👈 Move into your app folder
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            app-service/**              # 👈 Only include this folder
            !app-service/antenv/**       # 👈 Exclude virtual environment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3FBF467FEFA64D979A47125F1E72ABEF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C362AC2DB77340A69BB7798EC64A040F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D88A40E5BCB9444DBFCE719C79C0D230 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pocwebapp1'
          slot-name: 'Production'

